name: Docker Image CI

on:
  push:
    branches: [ "v0.6.x" ]
  pull_request:
    branches: [ "v0.6.x" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: cikaros/aria2-ext:v0.6.x